# Plug settings
plug:
  ip: "192.168.0.1" # Plug IP address
  username: "john.doe@gmail.com" # TP-Link app login username
  password: "myPasswordToTPLink" # TP-Link app login password

# IP addresses of devices used for check of online status
# - one of them must be online to perform power on
# - all of them must be offline to perform shutdown
check_ips: ["192.168.0.2"]

# How often controller pings devices to check their online status
refresh_interval: "PT3S" # ISO 8601 duration format, i.e.: PT1H2M3S = 1 hour, 2 minutes, 3 seconds

# Controller waits this time before actual shutting down. When the devices are offline in whole interval it performs shutdown
offline_delay_interval: "PT1H" # ISO 8601 duration format, i.e.: PT1H2M3S = 1 hour, 2 minutes, 3 seconds

# Log configuration
log:
  level: "INFO" # Log level
  file: "/var/log/tapo-controller/app.log" # Log file (optional)